# Generated by Django 3.0.7 on 2020-06-13 15:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('seance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seance',
            name='ends',
            field=models.DateField(default=datetime.datetime(2020, 6, 28, 15, 13, 8, 800642, tzinfo=utc), verbose_name='ends'),
        ),
        migrations.AlterField(
            model_name='seance',
            name='starts',
            field=models.DateField(default=datetime.datetime(2020, 6, 13, 15, 13, 8, 800601, tzinfo=utc), verbose_name='starts'),
        ),
    ]
