# Generated by Django 3.0.7 on 2020-06-13 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seance', '0002_auto_20200613_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seance',
            name='ends',
            field=models.DateField(verbose_name='ends'),
        ),
        migrations.AlterField(
            model_name='seance',
            name='starts',
            field=models.DateField(verbose_name='starts'),
        ),
    ]
