# Generated by Django 3.0.7 on 2020-06-17 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seance', '0002_auto_20200617_0508'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='row_number',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='row number'),
        ),
    ]
