# Generated by Django 3.0.7 on 2020-06-13 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seance', '0003_auto_20200613_1516'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seance',
            old_name='ends',
            new_name='date_ends',
        ),
        migrations.RenameField(
            model_name='seance',
            old_name='starts',
            new_name='date_starts',
        ),
    ]
