# Generated by Django 3.0.7 on 2020-06-17 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seance', '0003_ticket_row_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seance',
            name='places_taken',
        ),
    ]
