# Generated by Django 3.0.7 on 2020-06-15 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seance', '0007_advuser_last_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advuser',
            name='last_activity',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name="user's last activity was: "),
        ),
    ]
